### ISSUE TITLE
Can't enable DNS over HTTPS because the port 443 is in use

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/adguard_ynh#3]
### Steps to reproduce
1. Install Adguard on a server that already has another Yunohost app installed
2. On the Settings menu, click on "Enable encryption"
3. (Optional) Copy your domain's certificate and private key to the corresponding fields
4. Click Save

### Expected behavior
The encryption should begin working, and DNS-over-HTTPS should start to be served from https://example.net/adguard/dns-query .

### Actual behavior
The site warns that the port 443 is already in use and disallows continuing the configuration. If a port other than 443 is used, the DNS-over-HTTPS functionality no longer works on certain devices (such as Android 9 Pie).

### Your environment
|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.9.5-hotfix (manually updated from 0.9.2)

**Comment by liberodark** [comment]
for that use my pi hole fork have DoH :D

**Comment by liberodark** [comment]
And on 0.9.2 is DoH pre actived

**Comment by liberodark** [comment]
But for 0.9.2 wait for active this other need to use tls

**Comment by croulibri** [comment]
Hello,
I am not sure to fully understand the solution.

I have adguard install on a specific subdomain where only adguard is installed `adg.mydomain.com`
But I have other subdomain on my Yunohost server with other apps, some of them using port 443 on their subdomain.

Is there a way to use DoH with address like https://adg.mydomain.com/dns-query ?

**Comment by xplosionmind** [comment]
Hello, sorry for the late response, @liberodark and @croulibri, but I still am experiencing issues also in 0.107.2~ynh2…

<img width="1440" alt="Screenshot 2022-01-11 at 5 45 09 PM" src="https://user-images.githubusercontent.com/42862428/148985382-15851fe9-6257-432e-949d-0ada5c579bb0.png">


Is there anything I should do?

**Comment by elbubar** [comment]
Same issue here. Installed on a dedicated server.

**Comment by baboonandsloth** [comment]
i also have this problem

**Comment by TheNomad11** [comment]
Way has this issue been closed? The problem is still there?

**Comment by matlag** [comment]
So is it that it can't be fixed because of some Yunohost specificity or should this be re-opened?

**Comment by TheNomad11** [comment]
I tried again and I still see the same error message, although this issue was closed

**Comment by enzonaute** [comment]
the problem is still present in v0.107.21. **Why is the issue closed?**

**Comment by brzeziniol** [comment]
My workaround was to change ports in /var/www/adguardhome/AdGuardHome.yaml
1. stop adguard 
`sudo systemctl stop adguardhome.service`
2. edit config file
` sudo nano /var/www/adguardhome/AdGuardHome.yaml`
3. replace 
```
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
```
with
```
  port_https: 4430
  port_dns_over_tls: 8530
  port_dns_over_quic: 7840
```
4. save CTRL+O, exit CTRL+X
5. redirect ports 4430, 8530, 7840 on your router
6. start adguard
`sudo systemctl start adguardhome.service`

done.
