### ISSUE TITLE
Can't connect to admin user at AdGuard login webpage 

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/adguard_ynh#8]
I updated my Yunohost server.

I installed AdGuard through SSH with `sudo yunohost app install https://github.com/YunoHost-Apps/adguard_ynh`
I got the `Success! Installation complete`

I checked with `systemctl status adguard`
and received :
```
● adguard.service - adguard
   Loaded: loaded (/etc/systemd/system/adguard.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-11-22 20:37:12 UTC; 8min ago
 Main PID: 1551 (AdGuardHome)
    Tasks: 14 (limit: 4915)
   CGroup: /system.slice/adguard.service
           └─1551 /opt/yunohost/adguard/AdGuardHome
```
But then when I go to the login page of AdGaurd, I am received with a correct webpage, I enter username and password that I set during the install process and get
`Error: control/login | invalid login or password | 400`

I tried to uninstall and install again AdGuard without success to log in with my admin user.

Have you faced similar problem ?
How could I solve this issue ?

**Comment by liberodark** [comment]
use this version : https://github.com/YunoHost-Apps/adguard_ynh/tree/0.9.2

**Comment by croulibri** [comment]
Thanks !
I installed version 0.9.2. and I could connect to admin.
Then I upgraded to up-to-date version through  `$ sudo yunohost app upgrade adguard -u https://github.com/YunoHost-Apps/adguard_ynh`
... and I can still connect to admin interface.
Fantastic!

I am now interested in using DoH but I have the same issue as https://github.com/YunoHost-Apps/adguard_ynh/issues/3
